### ISSUE TITLE
얕은 잠을 자고있는지 여부를 소리를 통해 측정

### ISSUE THREAD

**Issue by Yeonji-Lim** [ProjectInTheClass/SleepWithAI#3]

**Comment by KimWanki** [comment]
CreateML 모델을 활용해 얕은잠과 깊은 잠 여부를 판정.
입력된 소리로부터 출력되는 분류 값들을 판단해 얕은 잠과 깊은 잠은 판단.
하지만, 완벽하게 얕은 잠과 깊은 잠을 구분짓는 정확한 범위 설정은 하지 않음.
